drop table FILM CASCADE CONSTRAINTS;
drop table ACTOR CASCADE CONSTRAINTS;
drop table FILM_ACTOR CASCADE CONSTRAINTS;
drop table FILM_CATEGORIES CASCADE CONSTRAINTS;
drop table FILM_CATEGORY CASCADE CONSTRAINTS;

